version: 2

models:
  - name: fact_coins
    description: >
      Data on all of the coins that are being tracked.

  - name: fact_btc
    description: >
      Averaged results per hour for Bitcoin.

  - name: fact_eth
    description: >
      Averaged results per hour for Etherium.

  - name: fact_usdt
    description: >
      Averaged results per hour for Tether.

  - name: fact_bnb
    description: >
      Averaged results per hour for BNB.

  - name: fact_usdcc
    description: >
      Averaged results per hour for USD Coin.

  - name: fact_xrp
    description: >
      Averaged results per hour for XRP.

  - name: fact_ada
    description: >
      Averaged results per hour for Cardano.

  - name: fact_doge
    description: >
      Averaged results per hour for Dogecoin.
      